### ISSUE TITLE
syslog4j-graylog2 pull request no longer needed?

### ISSUE THREAD

**Issue by coursera-ds** [jcustenborder/kafka-connect-syslog#1]
Is this still needed?  It appears to have been merged into syslog4j-graylog2.

"Unfortunately this requires the following pull request from syslog4j-graylog2. You will need to pull do this pull request and mvn clean install before building this project."

If not, the pom will need to be updated to remove '-SNAPSHOT' from the syslog4j-graylog2 version requirement.  I was able to successfully build this project by doing this.

**Comment by jcustenborder** [comment]
@coursera-ds Sorry about the slow response. I get an insane amount of github notifications so this was lost in the noise. This has been corrected and a new version with some cleanup and more features have been pushed.
