### ISSUE TITLE
How to install and use Kafka Connect Syslog

### ISSUE THREAD

**Issue by Dr-Crow** [jcustenborder/kafka-connect-syslog#13]
I recently just started to use Kafka and after playing around with their quick start guide I wanted to start send some syslog messages to Kafka. I came across your repo and want to utilize it in my environment. How do you install and use Kafka connect syslog?  I downloaded the deb file on your latest release and install it, but I am confused on how to get it to work with Kafka. I wanted to set up UDP and TCP non SSL syslog connectors. Could you point me in the right direction and get me started?

**Comment by Dr-Crow** [comment]
Did a little more digging but still having trouble. I set the class path to "/usr/share/java/*". Then I add the config file tcpsyslog.properties to the config folder with the following config:


```
name=tcpsyslog
tasks.max=1
connector.class=com.github.jcustenborder.kafka.connect.syslog.TCPSyslogSourceConnector
kafka.topic=syslog-tcp
syslog.port=1514
syslog.reverse.dns.remote.ip=true

# Set these required values
kafka.topic=honeypots

```

Finally, I start up zookeeper, then Kafka using the default config files.  Then I issue this command:

`./bin/connect-standalone.sh config/tcpsyslog.properties
`

But I am not sure if anything happened. I look at that ports the server listening too and 1514 is not there.  I am running this all on Ubunut 16.04.

**Comment by jcustenborder** [comment]
hi @Dr-Crow 

Take a look at this section [installing plugins](https://docs.confluent.io/current/connect/userguide.html#installing-plugins) section. Basically you will place the connectors in a certain path and and connect will load them on the start. Starting with 0.11 you have classpath isolation meaning you'll need to set `plugin.path=/usr/local/share/kafka/plugins` to something like this. Using this as an example you would create a directory `/usr/local/share/kafka/plugins/kafka-connect-syslog` with all of the jars for the connector. The next thing is connect standalone takes two files. The first file is the worker properties. Take a look [here.](https://github.com/jcustenborder/kafka-connect-syslog/blob/master/bin/debug.sh#L27). This is how I launch connect for development. Notice there is a worker config first and a connector config second. For example this repo has a docker-compose file and a config that that will write to kafka. You can use it as a starting point.
